
services:
  s3:
    image: adobe/s3mock:3.11.0
    ports:
      - "9090:9090"
    environment:
      - initialBuckets=deploy-bucket,test-bucket
      - root=/data
    volumes:
      - ./.tmp/s3:/data
