stages:
  myapp-dev:
    spaDeploy:
      aws:
        region: us-east-1
        accountId: 00000000000

      s3:
        # acl: "public-read"
        bucket: EXAMPLE_BUCKET

      cloudfront:
        distributionId:
          - EXAMPLE_DIST_ID
        invalidatePaths:

    spaIndexGlob: index.html

    # inject variables into the website
    spaGlobals:
      # APP_STAGE: automatic via stage
      # APP_VERSION: automatic via appVersion option
      # APP_RELEASE: automatic via git
      EXAMPLE: thing

    slackNotify:
      channel: C0EXAMPLE
      autolinkPrefix: SP-
      autolinkTarget: https://github.com/poviolabs/spa-deploy-cli/issues/
      commitPrefix: https://github.com/poviolabs/spa-deploy-cli/commit/
      projectName: SPA-Deploy
