name: "Deploy Development"

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy Development
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: ./.github/actions/spa-deploy
