version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.0

jobs:

  build-and-deploy: &build-and-deploy
    docker:
      - image: circleci/node:14.15
    steps:
      - checkout

      # Install packages
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install --immutable
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unplugged

      # Run tests/eslint
      # - run: npm run task:eslint

      - run: npm run build

      # RUN DEPLOY SCRIPT
      #  add version and variables to header
      #  create targeted invalidations
      - run:
          name: Deploy to S3
          command: yarn spa-deploy-cli

  goodcontent-dev:
    <<: *build-and-deploy
    environment:
      STAGE: goodcontent-dev

  goodcontent-stg:
    <<: *build-and-deploy
    environment:
      STAGE: goodcontent-dev

workflows:
  version: 2
  build-and-deploy:
    jobs:

      - goodcontent-dev:
          filters:
            tags:
              ignore: /.*/
            branches:
              only: goodcontent-dev

      - goodcontent-stg:
          filters:
            tags:
              ignore: /.*/
            branches:
              only: goodcontent-stg
